### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [giorgionicoletti/deep_Q_learning_maze#1]
The jupyter notebook crashes because agent.py does not import torch, but refers to torch.Tensor.

**Comment by keithbriggs** [comment]
Even after importing torch, it still does not work, because Transition is not defined in agent.py.

**Comment by giorgionicoletti** [comment]
Thanks for noticing. It's a code that I wrote quite some time ago just for fun, it's very likely that there are going to be import issues like these since I rewrote part of it in an effort to make it more readable before uploading it to github. They should be quite easy to fix though.

**Comment by keithbriggs** [comment]
Ok, I am trying to fix it now.

________________________________

**Comment by giorgionicoletti** [comment]
The import errors in agent.py are now completely fixed, you should be able to train without any problem now.

**Comment by keithbriggs** [comment]
Thank you!
