### ISSUE TITLE
Can't train model

### ISSUE THREAD

**Issue by Thanh2602** [giorgionicoletti/deep_Q_learning_maze#2]
Hi
When i build code in google colab, the issue is happened "NameError: name 'torch' is not defined".
It notice This line "state = torch.tensor(self.env.state()).to(device).view(1,-1)" in agent.py is error .
I try to fix but it still error 
Can you help me fix this.
My link colab : https://colab.research.google.com/drive/1B8MvhLxLb-WY1HKzUvs8gVrxqQ22ElxE?usp=sharing
Thanks

**Comment by giorgionicoletti** [comment]
The import errors in agent.py are now fixed.
